version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dwh
    ports:
      - '5433:5432'
    volumes:
      - python-postgresql_db:/var/lib/postgresql/data
volumes:
    python-postgresql_db: # docker volume create postgres_data
      external: true
